### ISSUE TITLE
collector fails on error records in the access.log

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/webproxy#188]
```
Traceback (most recent call last):
  File "M:\webproxy-core\src.mon\bin\monitor\collector\entry_factory.py", line 208, in construct
    self.set_sizes(entry, data)
  File "M:\webproxy-core\src.mon\bin\monitor\collector\entry_factory.py", line 94, in set_sizes
    entry.request_size = data["request"]["counters"]["read"]
KeyError: 'counters'
```

**Comment by ra-at-diladele-com** [comment]
It works on records from 0.10 normally.
