### ISSUE TITLE
Monthly and yearly stats are not shown in traffic monitor (error from waitress)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/webproxy#197]

**Comment by ra-at-diladele-com** [comment]
```
2021-03-23 07:42:57,373 Exception while serving /history/month/2021-03/summary/
Traceback (most recent call last):
  File "waitress\channel.py", line 397, in service
  File "waitress\task.py", line 168, in service
  File "waitress\task.py", line 434, in execute
  File "flask\app.py", line 2464, in __call__
  File "whitenoise\base.py", line 85, in __call__
  File "flask\app.py", line 2450, in wsgi_app
  File "flask\app.py", line 1867, in handle_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "monitor\console\routes_history.py", line 242, in history_month_summary
  File "flask\templating.py", line 138, in render_template
  File "jinja2\environment.py", line 930, in get_or_select_template
  File "jinja2\environment.py", line 883, in get_template
  File "jinja2\environment.py", line 857, in _load_template
  File "jinja2\loaders.py", line 115, in load
  File "flask\templating.py", line 60, in get_source
  File "flask\templating.py", line 89, in _get_source_fast
jinja2.exceptions.TemplateNotFound: history_month/summary.html
2021-03-23 07:43:03,471 Exception while serving /history/year/2021/summary/
Traceback (most recent call last):
  File "waitress\channel.py", line 397, in service
  File "waitress\task.py", line 168, in service
  File "waitress\task.py", line 434, in execute
  File "flask\app.py", line 2464, in __call__
  File "whitenoise\base.py", line 85, in __call__
  File "flask\app.py", line 2450, in wsgi_app
  File "flask\app.py", line 1867, in handle_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "monitor\console\routes_history.py", line 356, in history_year_summary
  File "flask\templating.py", line 138, in render_template
  File "jinja2\environment.py", line 930, in get_or_select_template
  File "jinja2\environment.py", line 883, in get_template
  File "jinja2\environment.py", line 857, in _load_template
  File "jinja2\loaders.py", line 115, in load
  File "flask\templating.py", line 60, in get_source
  File "flask\templating.py", line 89, in _get_source_fast
jinja2.exceptions.TemplateNotFound: history_year/summary.html
```

**Comment by ra-at-diladele-com** [comment]
Seems the installer did not have the yearly/monthly templates.

**Comment by ra-at-diladele-com** [comment]
Added to the MSI, need to check.
