### ISSUE TITLE
After updater updated the ccadb we need to restart webproxyd service (not just reload)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/webproxy#269]

**Comment by ra-at-diladele-com** [comment]
Implemented, need to check.

**Comment by ra-at-diladele-com** [comment]
Error ACCESS DENIED
```
2021/05/01 06:30:18 SUCCESS:
2021/05/01 06:30:18 SUCCESS: Updater completed successfully! Update status: %!s(int=2)
2021/05/01 06:30:18 SUCCESS:


05/01/2021 06:30:18 Updater c:\Program Files\Diladele\Web Filtering Proxy\updater.exe finished with exit code 2
05/01/2021 06:30:18 Updater completed normally, some new definition files were downloaded
05/01/2021 06:30:18 Restarting the Web Filtering Proxy service (disable the schedule task if this is inappropriate) ...
05/01/2021 06:30:18 Successfully opened the 'webproxyd', its status is 'Running'.
05/01/2021 06:30:18 Stopping service...
05/01/2021 06:30:22 Service could not be stopped, error: System.InvalidOperationException: Cannot open webproxyd 
service on computer '.'. ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.Stop()
   at Diladele.Wfp.Updater.Restarter.Restart(Boolean only_reload) in M:\webproxy-core\src.ui\Diladele.Wfp.Updater\Restarter.cs:line 61
05/01/2021 06:30:22 Starting service...
05/01/2021 06:30:22 Service could not be started, error: System.InvalidOperationException: Cannot start service webproxyd 
on computer '.'. ---> System.ComponentModel.Win32Exception: An instance of the service is already running
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at Diladele.Wfp.Updater.Restarter.Restart(Boolean only_reload) in M:\webproxy-core\src.ui\Diladele.Wfp.Updater\Restarter.cs:line 72

```

**Comment by ra-at-diladele-com** [comment]
Updater is set to be running as LOCAL SYSTEM account instead of NETWORK SERVICE. Have verified updating including restart and reload. Seems to be ok. Closing.
