### ISSUE TITLE
License check fails with strange error

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/webproxy#572]
```
System.Exception: License key is invalid, please click Proxy Settings / License Key. License Info: System.ArgumentException: Invalid JSON primitive: .
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at Diladele.Wfp.Data.License.Instance(String licenseKeyPem)
   at Diladele.Wfp.MmcSnapIn.BusinessLogic.HealthChecker.CheckLicense()
```

**Comment by ra-at-diladele-com** [comment]
Added more debugging output; lets see if this is reproduced.

**Comment by ra-at-diladele-com** [comment]
yes fixed
